# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"double": "00_core.ipynb",
         "triple": "00_core.ipynb",
         "power": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://randomgeek78.github.io/nbdev_rg78/"

git_url = "https://github.com/randomgeek78/nbdev_rg78/tree/master/"

def custom_doc_links(name): return None
