# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['double', 'triple']

# Cell

def double(x):
    """Doubles an input number

    >>> double(2)
    4
    """
    return x * 2

# Cell

def triple(x):
    """ Triples an input number

    >>> triple(3)
    9
    """
    return x * 3